sandboxnu/course-catalog-api

- graphql/index.js
- prisma/.env
- prisma/schema.prisma
- scripts/migrate_major_data.ts
- serializers/courseSerializer.js
- serializers/hydrateSerializer.js
Added prisma schema and fixed a couple prisma import statements.
Apparently an Apollo Server from `apollo-server-express` doesn't have a listen() method, so I switched to using `apollo-server`.
> Got GraphQL Up!

- package.json
- services/updater.ts
- tests/updater.test.seq.ts
The updater was only updating courses/sections for undergrad classes in spring 2021. We want to update courses for Law and CPS as well.
> Update Multiple Terms

- Dockerfile
- infrastructure/aws/push-image
- infrastructure/aws/redeploy
- infrastructure/aws/run-task
- infrastructure/aws/scrape
- infrastructure/terraform/acm.tf
- infrastructure/terraform/modules/course-catalog-api/rds.tf
- package.json
Mostly terraform and infrastructure changes
> update package.json & Terraform updates

- graphql/index.js
> Update GraphQL Condition for Prod

- package.json
Run `yarn build` before running updater in prod
> Fix Prod Updater

- services/updater.ts
- tests/updater.test.seq.ts
Include the termId `202210` as something the updater should update along with the current summer terms. Fix updater tests.
> Updater Should Update Fall 2021

- infrastructure/readme.md
- infrastructure/terraform/modules/course-catalog-api/elasticsearch.tf
- scrapers/classes/parsersxe/classParser.js
- scrapers/classes/parsersxe/sectionParser.js
- scrapers/classes/parsersxe/termParser.js
- scrapers/classes/parsersxe/util.js
- scrapers/classes/processors/tests/markMissingPrereqs.test.js
- scrapers/employees/employees.js
- scrapers/employees/matchEmployees.js
- scrapers/employees/util.ts
- scrapers/tests/__mocks__/request-promise-native.js
- services/searcher.ts
- services/updater.ts
- tests/updater.test.seq.ts
Don't create IAM role for prod elasticsearch since we ran Terraform once already.
> Debug AWS Elasticsearch

- infrastructure/readme.md
- scrapers/classes/parsersxe/classParser.js
- scrapers/classes/parsersxe/sectionParser.js
- scrapers/classes/parsersxe/termParser.js
- scrapers/classes/parsersxe/util.js
- scrapers/classes/processors/tests/markMissingPrereqs.test.js
- scrapers/employees/employees.js
- scrapers/employees/matchEmployees.js
- scrapers/employees/util.ts
- scrapers/tests/__mocks__/request-promise-native.js
- services/searcher.ts
- services/updater.ts
- tests/updater.test.seq.ts
Started a ReadMe documenting steps taken to migrate the infrastructure to a new AWS account. Merging to trigger terraform run.
> ReadMe For Infrastructure Migration

- infrastructure/terraform/staging.tf
change domain from `staging.api.searchneu.com` to `stagingapi.searchneu.com`
> Set up staging CCA

- services/updater.ts
The updater process currently hangs in prod for some unknown reason. This is annoying because then I have to remember to kill the ECS task daily to spawn a new one that works for a little while. This PR adds some logging and kills the process if the updater errors instead of attempting to run the updater again.
> Improve Updater

- documentation/infrastructure/accessing_the_jumphost.md
This PR clarifies how to add a new SSH key to the jumphost.
> clarify how to add a new SSH key to the jumphost

- services/prisma.ts
- utils/macros.ts
See https://github.com/sandboxnu/course-catalog-api/pull/91
> Prisma fix #6 (trust me this is the one)

- services/prisma.ts
- services/updater.ts
- utils/macros.ts
> Prisma fix #7 (I hate this)

- .github/workflows/docker.yaml
- .github/workflows/test.yaml
- infrastructure/prod/entrypoint.sh
<br>
Creates a workflow test which builds the Docker image from scratch, checks that it works, and attempts live scraping (ie. against Banner, not against a cache). 
-https://trello.com/c/0q3bYmUp/320-improve-scrapers-story
- @hankewyczz 
- Builds and tests the Docker container
-Scrapes against the live Banner API (network-dependent)
-
<br>
<br>
> Add workflow test to build Docker image, and run live scraping

- scrapers/classes/main.ts
- scrapers/classes/processors/addPrerequisiteFor.ts
- scrapers/classes/processors/markMissingRequisites.ts
- scrapers/classes/processors/simplifyPrereqs.ts
- scrapers/classes/processors/tests/addPrerequisiteFor.test.js
- scrapers/classes/processors/tests/markMissingPrereqs.test.js
- scrapers/classes/processors/tests/simplifyPrereqs.test.ts
> Part 2 - Refactoring course processors

- .eslintrc.js
- graphql/tests/class.test.seq.ts
- graphql/tests/major.test.seq.ts
- graphql/tests/search.test.seq.ts
- package.json
- scripts/migrate_major_data.ts
- services/updater.ts
- tests/dumpProcessor.test.seq.ts
- tests/macros.test.ts
- tests/updater.test.seq.ts
- tsconfig.json
- yarn.lock
<br>
Our existing `tsc` setup was only checking a subset of the files - I never switched this over when I did the Typescript conversion. 
- N/A
- @hankewyczz
> Properly enable `tsc` checks

- docs/_sidebar.md
- docs/banner/apiSpec.html
- docs/banner/banner.md
- docs/index.html
<br>
Expand our documentation about Banner
- @hankewyczz 
<br>
> Add documentation about Banner

- docs/getting-started/running.md
- template.env
<br>
Our docs are not clear about our `.env` configuration, and why it's necessary
> Small documentation tweaks 

- Dockerfile
- tests/end_to_end/elastic.test.git.ts
>   Revert #103

- scrapers/classes/parsersxe/bannerv9Parser.ts
- scrapers/classes/parsersxe/classParser.ts
- scrapers/classes/parsersxe/sectionParser.ts
- scrapers/classes/parsersxe/subjectAbbreviationParser.ts
- scrapers/classes/parsersxe/termParser.ts
- scrapers/classes/parsersxe/util.ts
- scrapers/employees/employees.ts
- scrapers/request.ts
- scrapers/tests/request.test.js
- tests/end_to_end/elastic.test.git.ts
We'll be replacing our internal requests library! To help prepare for it, this PR simplifies its functionality (before we replace it).
<br>
- https://trello.com/c/wKeHrjJH/314-replace-request-library
> Simplify `RequestInput` in preparation for replacing the requests library

- docs/_sidebar.md
- docs/infrastructure/migration/migration.md
- docs/infrastructure/migration/staging-migration.md
- docs/infrastructure/scraping.md
- infrastructure/terraform/variables.tf
Based on how the migration process went yesterday, these docs reflect new knowledge/clarification about the whole process.
> Update migration docs

- docs/getting-started/running.md
> Update setup docs to reflect AirPlay server

- .github/workflows/docker.yaml
- .github/workflows/test.yaml
- docs/getting-started/running.md
- infrastructure/dev/docker-compose-server.yml
- infrastructure/dev/docker-compose.yml
- prisma/.env
- prisma/schema.prisma
- template.env
<br>
- https://hub.docker.com/_/postgres
- https://www.postgresql.org/docs/14/auth-trust.html
With our PSQL upgrade (#149), the default will throw an error if no Postgres password is provided. 
For local development, we don't use a password (this is not true for prod/staging). While we *could* override this setting with no issue, it's safer to default to a password. 
This only affects each user's local development environment, which is at very low-risk for access and/or misuse (all data is public anyways). 
- N/A
- @hankewyczz 
<br>
> Add `POSTGRES_PASSWORD`

- docs/deployment/deploy.md
> Update docs to more throughly describe the backend AWS deployment process

- docs/getting-started/prereqs.md
Update the documentation with basic info about how to enable scheduled reminders between Github and Slack.
_What Trello tickets (if any) are associated with this PR?_
- N/A
> Update documentation with information about Slack integration

- scrapers/classes/parsersxe/bannerv9Parser.ts
Minor tweak to reduce unnecessary logging in Prod
> Remove prod logging

- prisma/.env
Having intermittent issues with Prisma timeouts — bumping the connection timeout has proved helpful.
> Bump the Prisma connection timeout

- .github/workflows/test.yaml
- docs/getting-started/running.md
- scrapers/classes/parsersxe/bannerv9Parser.ts
- scrapers/classes/parsersxe/tests/bannerv9Parser.test.ts
- scrapers/main.ts
- services/dumpProcessor.ts
- tests/database/dumpProcessor.test.seq.ts
- types/types.ts
Reverts #183, which was accidentally merged due to a write permissions issue.
> Revert #183

- services/updater.ts
We'll need to do some refactoring in this file in the future. 
To make this easier — both to write and to understand — we'll want to break the updater into smaller functions first. That's all this PR does — breaks the functionality into smaller, bite-sized functions.
> Break the updater into smaller functions for future refactoring

- infrastructure/terraform/jumphost.tf
- infrastructure/terraform/modules/course-catalog-api/elasticsearch.tf
- infrastructure/terraform/modules/course-catalog-api/rds.tf
- infrastructure/terraform/modules/course-catalog-api/variables.tf
Back in Nov-Dec 2022, we had to cut back on our AWS instances due to cost pressures. 
However, we shouldn't be running at these lower levels for a long time - we have way too many users for what we have to work properly. This is compounded by Graduate releasing their product to the public (congrats!!) so we need a few upgrades.
> Upgrade AWS instances

- scrapers/employees/employees.ts
Updates the api version for fetching employees. Currently master doesn't properly scrape employees because the api version is outdated. This fixes that.
@pranavphadke1
- updated api version for employee api to match the payload request exposed at https://nu.outsystemsenterprise.com/FSD/ 
**Primary**:
@Lucas-Dunker 
@sebwittr 
**Secondary**:
@allychao
> Update API version for employee API scraper

- scrapers/classes/classMapping.json
During our most recent SearchNEU outreach event, we got some new course abbreviations to add to the site! 
[Ticket](https://trello.com/c/v5U6vPPy/415-add-in-new-course-abbreviations)
@Lucas-Dunker 
* Add new course abbreviations
**Primary**:
@sebwittr 
**Secondary**:
@allychao @pranavphadke1
> Add new course abbreviations

- scrapers/employees/matchEmployees.ts
Received a request to filter out an employee's contact information
- https://trello.com/c/IDqNLgZz
@sebwittr @pranavphadke1
> filter out employee
