- Keys.js
- graphql/resolvers/class.ts
- graphql/tests/__snapshots__/class.test.seq.ts.snap
- graphql/tests/class.test.seq.ts
- graphql/typeDefs/class.js
SearchNEU wants to query for course/sections based on the course hash and section hash.
Added support for graphql to handle these types of queries.
> graphql support querying course/section based on coursehash/sectionhash

- graphql/typeDefs/classOccurrence.js
SearchNEU needs the GraphQL classOccurrence and Section typedefs to have some additional properties.
See https://github.com/sandboxnu/searchneu/pull/83
> Add fields to GraphQL typedefs to convert search over to GraphQL

- graphql/resolvers/class.ts
For class pages, we want to make the `class(subject: String!, classId: String!)` graphQL query instead of the standard `search` query. The resolvers on the ClassOccurrences were not returning Section info, causing the desired query to get an error response.
Add `include: { sections: true }` in prisma in all the resolvers that return a ClassOccurrence.
The GraphQL typedef for Sections includes a `termId` field but the Sections in ClassOccurrences returned from resolvers do not have this field.
> Add Sections For ClassOccurrence Resolvers

- scrapers/classes/parsersxe/classParser.js
Scrapers were reversing minCredits and maxCredits
If minCredits and maxCredits are the same, scrapers will get 0 for `creditHourHigh` and the number of credits for `creditHourLow`. Therefore `maxCredits` should be `creditHourHigh` if it exists and `creditHourLow` otherwise.
> Fix Scrapers For Min/Max Credits

- services/updater.ts
The notification info wasn't being sent in the request to Search's notifyer.
Just do `req.end(body)` instead of `req.write(body)`. Also for local dev work, the request should be http not https.
- If there isn't one already, we need a `WEBHOOK_PRIVATE_KEY` environment variable and `UPDATER_URL` on prod
Run this command in your terminal `ssh-keygen -m PEM -t rsa -b 4096 -C "youremail@example.com"`, type in the name of the file you want the keys to be in, and your private key will be named `yourFileName.pub` and your public key will be named `yourFileName`
> Fix How Updater Sends NotificationInfo to Notifyer

- Dockerfile
The updater was exiting early on AWS, we want to fix that.
The Dockerfile wasn't copying the `scripts` folder, so we add a line to copy it.
> Copy scripts folder in Dockerfile

- graphql/typeDefs/classOccurrence.js
Previously, the type definition for a Course in GraphQL had integer `classId`s. This is a problem because there are classes like `ESLG 0045` whose classId should be `0045`, not `45`. Right now, CCA is sending the wrong classId for classes like `ESLG 0045` so this PR addresses the bug.
> Make Course ClassId String instead of Int

- services/updater.ts
Previously added some logs to see what private webhook key, updater URL were. No longer need this so this PR is removing some of those logs.
> Removing Updater Logs That Were Added For Debugging Prod

- graphql/typeDefs/classOccurrence.js
- graphql/typeDefs/search.js
termId was defined as an int in some places and as a string in other places. Made back end changes that keep termId as a string consistently.
> Make termID defined as String consistently 

- prisma/migrations/20211119161621_delete_cascade/migration.sql
- prisma/schema.prisma
- services/dumpProcessor.ts
- yarn.lock
Deleting stale courses / sections was breaking because prisma doesn't do cascade delete and in prod, there were records in `followed_courses` and `followed_sections` that point to stale courses / sections.
prisma 3.x.x supports delete cascade in the schema but this would require a migration from prisma 2.x.x and there are some breaking changes that I don't want to figure out now since it's getting annoying to keep deleting the ECS updater task. This PR enables a preview feature for referential actions and updates the schema to handle delete cascade.
TODOs: upgrade prisma to 3.x.x and also typescript so prisma client types work again.
> Enable Delete Cascade

- services/updater.ts
Updater hangs in prod and errors weren't being caught.
Properly await the `update()` method, catch error, and exit the process on error. This will force AWS to spin up a new ECS task for the updater.
> properly await update, catch error, exit on error

- services/notificationsManager.ts
- twilio/notifs.ts
Updater crashes when trying to send notifications to a user who unsubscribed by replying "STOP".
Catch that specific error from Twilio and delete the user's subscriptions.
> Fix Updater Error If User Unsubscribes From Notifs

- infrastructure/terraform/modules/course-catalog-api/ecs.tf
Comment out cron job for scrapers. 
Scrapers don't work on prod, they just hang and this cron job causes a new scraper task to spin up every day, resulting in lots of stale scraper tasks.
This shouldn't change much (if anything) on AWS because I manually deleted the cron job a while ago because I was getting annoyed with manually deleting stale scraper requests every few days.
> Remove cron job for scrapers

- infrastructure/dev/docker-compose-server.yml
- twilio/server.ts
The feedback/contact buttons do not work. This adds a feedback endpoint to the notifs server, which notifies the Search team on Slack.
<br>
https://trello.com/c/MzKg5kJT/288-feedback-buttons-are-inactionable
- @hankewyczz 
<br>
<br>
> Add endpoint for posting feedback

- README.md
- documentation/onboarding_setup.md
- utils/elastic.ts
- Fixes an issue with the updater and elastic client where initial setup of indices was not occurring. Now, any bulk upsert will first check the existence of any blue/green index, and create them when necessary.
- Abstracts the naming and mapping of the index away from all business logic on elastic.ts so it only resides in the constructor (in case we need a future edit to indices as a whole)
-  Cleans up some more of `elastic.ts`
> add initializing indices if not existing

- services/prisma.ts
- utils/macros.ts
<br>
This is going to be the main Prisma bugfix PR. I'm detailing the history, research, and random stuff here. 
Prisma connection pool is acting up. This has happened before (see [this error from June 2021](
https://rollbar.com/ryanhugh/searchneu/items/3868/)), but I think we had other issues covering it up, so we didn't notice
Other Rollbar issues:
- https://rollbar.com/ryanhugh/searchneu/items/3868/
- https://rollbar.com/ryanhugh/searchneu/items/3887/
- https://rollbar.com/ryanhugh/searchneu/items/3958/
This is unexpected Prisma behavior. Normally, when the connection pool is full, the queries just die until the pool clears up. In our case, it never recovers from this state. 
Two related issues on GitHub:
- https://github.com/prisma/prisma/issues/7249
- …
> Temp Prisma fix

- scrapers/employees/employees.ts
- services/dumpProcessor.ts
3 issues:
- Update the `moduleVersion`
- Don't delete professors if prodDump is empty (ie. when the updater runs)
- Exclude the `office` key, which exists in some of our old employee data
> Tweaks to fix staging employee insertion

- pull_request_template.md
Update the PR template.
Some of the checkboxes (linting, type checking, existing tests, test coverage) are all checked by the Github workflow, and can't be merged without them. (So, no longer necessary in the template)
> Update PR template (tiny PR)

- scrapers/classes/parsersxe/bannerv9Parser.ts
- utils/macros.ts
<br>
Allow developers to override defaults for scraping and updating.
By default, we scrape/update the 12 newest terms.
Using `NUMBER_OF_TERMS`, devs can specify how many of the newest terms should be scraped.
Using `TERMS_TO_SCRAPE`, devs can provide a comma-delimited string of terms to scrape. 
- https://trello.com/c/0q3bYmUp/320-improve-scrapers-story
- @hankewyczz
> Allow devs to specify which semesters to scrape, or the number of semesters to scrape

- services/searcher.ts
- tests/__snapshots__/search.test.seq.ts.snap
- tests/search.test.seq.ts
- types/searchTypes.ts
Added the capabilities for phrase searching to the project. If a query has a phrase within quotes, the searcher will search using a match_phrase query. Every result must contain the contents of a phrase. 
To replicate locally, run yarn dev on the backend, and yarn dev:fullstack on the front end. You can search data structures, and see that discrete structures comes before it. If you search "data structures", it'll be the only result on the page. 
<br> 
- https://trello.com/c/lYrJEVja/269-add-phrase-searching
- @sebwittr 
- @andrewydai 
- Added a parser function to the searcher, which broke down queries to phrase queries and non-phrase queries
- Created a QueryWithType type, which was either "phrase" or "most_fields".
- New query structure requires result to include phrase, and should have …
> add phrase searching to searcher

- .github/workflows/test.yaml
Bump for Coveralls in verbose. Merging without review, since the changes are trivial.
> Coveralls bump

- graphql/resolvers/termInfo.ts
- services/dumpProcessor.ts
- services/searcher.ts
- tests/end_to_end/search.test.git.ts
- utils/abstractMacros.ts
<br>
- Good news: SearchNEU is popular, widely used, and sees a significant jump in usage as students return to classes.
- Bad news: Prisma can only handle 15 simultaneous connections.
We make direct Prisma calls in two cases:
- when fetching the semester information (ie. on every single page onload)
- when searching for a specific single class (eg. "CS3500")
This isn't scalable - we need to reduce our direct usage of Postgres (add caching/use elasticsearch)
This ticket removes them both 
- N/A
- @hankewyczz 
<br>
> Remove direct PSQL calls

- docs/getting-started/running.md
- docs/getting-started/stored-cache.md
<br> 
Updates our documentation to reflect the new cache setup
https://github.com/sandboxnu/searchneu/issues/87
- https://trello.com/c/bepEDdVz/316-add-caches-of-past-terms-to-github
- @hankewyczz 
-
-
-
<br>
<br>
> Update docs to reflect new `cache` archive

- graphql/resolvers/class.ts
- graphql/tests/__snapshots__/class.test.seq.ts.snap
- graphql/tests/class.test.seq.ts
- graphql/typeDefs/class.js
<br>
Adds a `bulkClasses` query to the course-catalog-api. Requested by the Graduate team [(see here)](https://github.com/sandboxnu/graduatenu/issues/472)
```gql
query Query {
bulkClasses(input: [{ subject: "CS", classId: "3000"}, {subject: "CS", classId: "2500"}]) {
name
classId
subject
latestOccurrence {
termId
}
}
}
```
will return
```json
{
"data": {
"bulkClasses": [
{
"name": "Fundamentals of Computer Science 1",
"classId": "2500",
"subject": "CS",
"latestOccurrence": {
"termId": "202310"
}
},
{
"name": "Algorithms and Data",
"classId": "3000",
"subject": "CS",
"latestOccurrence": {
"termId": "202310"
}
}
]
}
}
```
- N/A
- @hankewyczz
> Allow querying for classes in bulk

- scrapers/employees/employees.ts
- types/types.ts
<br>
Northeastern's faculty API has introduced a new field, `LongPositionTitle`, which didn't exist before. They also made one parameter (`PositionTitle`) optional. 
- @hankewyczz 
<br>
> Update NEU Faculty API syntax

- infrastructure/terraform/modules/course-catalog-api/domain.tf
- infrastructure/terraform/modules/course-catalog-api/variables.tf
- infrastructure/terraform/prod.tf
- infrastructure/terraform/staging.tf
<br>
Update Terraform to properly forward data requests to the webserver. 
The webserver container in AWS deploys both the GraphQL API and the notifications server (on different ports). To forward them, we create rules based on the forwarding domain. 
So — `notifs.searchneu.com` should be forwarded to the notification server, and `api.searchneu.com` should be forwarded to the GraphQL API. 
We were having an issue with the staging notifications — the notifications were being forwarded to the GraphQL API.
The issue was with how our domains were declared in Terraform. @hankewyczz made changes to Terraform during the migration to ensure that `notifs.searchneu.com` was getting a Cloudflare cert (before that, this wasn't configured in Terraform). However, this had the side-effect of messing up …
> Update Terraform behavior to properly forward notification server traffic

- infrastructure/terraform/modules/course-catalog-api/ecs.tf
We haven't run scrapers in AWS for a while. The ticket in Trello doesn't actually explain why. I'm re-enabling the scrapers to try troubleshooting.
_What Trello tickets (if any) are associated with this PR?_
- https://trello.com/c/XXAZ5Xx5/207-get-scrapers-working-on-prod
> Re-add scrapers back to prod

- .eslintrc.js
- services/dumpProcessor.ts
- tests/database/dumpProcessor.test.seq.ts
- types/scraperTypes.ts
- types/types.ts
When working with Prisma, a common pattern we had littered around was `variable as unknown as Prisma.<type>`. 
Essentially, Typescript wouldn't let us cast to `Prisma.<type>`, so casting to `unknown` first allowed us to _force_ the conversion.
Needless to say, that's a bad idea. This removes that behavior by adding explicit conversion functions
_What Trello tickets (if any) are associated with this PR?_
- N/A
Secondary reviewers: @soulwa
> Remove hacky Typescript conversions when working with Prisma

- scrapers/classes/main.ts
- scrapers/classes/parsersxe/bannerv9Parser.ts
- scrapers/classes/parsersxe/tests/bannerv9Parser.test.ts
- scrapers/classes/tests/classScraper.test.ts
- scrapers/main.ts
- services/updater.ts
Our Banner parser has some code that shouldn't logically be there. This PR just shuffles code around to make the organization more intuitive. 
The Banner parser _used to_ be responsible for determining what terms should be scraped. That's irrelevant to parsing, and this functionality should belong to the scraper itself. 
- Pick one primary reviewer
- The team member with the most relevant knowledge about the code area this PR touches
- **NOT** an author of the PR
- If the primary reviewer is the project lead, _select two primary reviewers_
- Goal: facilitate knowledge transfer to other team members
- Primary reviewers **are required to approve the PR** before it can be merged
**Primary**:
Use the …
> Move code determining which terms to scrape up out of the Banner parser

- infrastructure/terraform/modules/course-catalog-api/rds.tf
- scrapers/classes/tests/classScraper.test.ts
- scrapers/main.ts
- services/updater.ts
- tests/end_to_end/elastic.test.git.ts
Our scrapers used to be divided:
- Scraping scrapes class data
- Updating scrapes section data
Now, with #190, that line has been blurred. Once a term is scraped initially, the updater will automatically scrape any new classes _for that term_.
Therefore, there's no need to scrape a term more than once anymore (unless the class titles, descriptions, etc. change).
So, we should default our scrapers to only scrape __NEW__ terms. Of course, this can be overridden by several env. variables.
- Pick one primary reviewer
- The team member with the most relevant knowledge about the code area this PR touches
- **NOT** an author of the PR
- If the primary reviewer is the project lead, _select two primary reviewers_
- …
> By default, the scraper should only scrape new terms

- scrapers/classes/tests/classScraper.test.ts
- scrapers/main.ts
- services/updater.ts
The scraping changes made it so the default for the scraper only counted terms with no data, but neglected to omit old terms. There are terms for which we don't have data AND we don't care (eg. things over 3-4 years old).
> Tweak default scraping behavior

- docs/infrastructure/scraping.md
Minor fixes to our docs for scraping in Prod
@Lucas-Dunker 
**Primary**:
@sebwit20 
**Secondary**:
@pranavphadke1
> Scraping Docs Corrections

- .github/workflows/docker.yaml
- infrastructure/dev/docker-compose-server.yml
- infrastructure/dev/docker-compose.yml
- infrastructure/terraform/modules/course-catalog-api/rds.tf
- scrapers/employees/employees.ts
In preparation for migrating our AWS stuff, I noticed that there was a mismatch between our local and hosted posgres versions; our local postgres is `11.17`, but our hosted version is `11.19`! This PR updates everything to be universally `11.19`.
@Lucas-Dunker 
_Update our postgres version to 11.19
_Is there anything reviewers should note? Do we need to add something later? Any followups? Was this ticket easier/harder than predicted?_
**Primary**:
@sebwit20 
**Secondary**:
@pranavphadke1  @allychao
> Update Postgres Version

- scrapers/classes/parsersxe/classParser.ts
- scrapers/classes/parsersxe/sectionParser.ts
- scrapers/classes/parsersxe/tests/__snapshots__/classParser.test.js.snap
- scrapers/classes/parsersxe/tests/__snapshots__/sectionParser.test.js.snap
- scrapers/request.ts
Northeastern changed their provider for CRN data in their courses, meaning that all of our URL's no longer work. This ticket changes our scraper to get URL's from their new provider. 
[Ticket](https://trello.com/c/ih7pTGzg/409-crns-dont-work-anymore)
@Lucas-Dunker 
* Replace the old, now-defunct CRN link to the new, functional one. 
**Primary**:
@sebwittr @pranavphadke1 
**Secondary**:
@ananyaspatil
> Update scraped course data with new CRN link

- services/searcher.ts
In returned results, only show specific sections that match all filters of the classes with at least one section that matches filters.
Before:
After:
Addresses #233 
@Anzhuo-W 
When campus filters are applied, sections are only displayed for that campus instead of all sections for a course where at least one section is on that campus. The sections are filtered out from the results after they are returned by query; additionally applies to honors sections, class type, and subject.
@ananyaspatil 
Secondary reviewers:
@nickpfeiffer05 @cherman23 @mehallhm
> Add section filters

- services/notificationsManager.ts
- tests/database/notificationsManager.test.seq.ts
Count only active term notifications to unblock users from being unable to sub/unsub to notifications because of subscriptions created in prior semesters.
> count only active term notifications

- tests/general/twilio.test.ts
- twilio/notifs.ts
The code adds logic to unsubscribe phone number from notifs when STOP_ALL reply.
#249 
@ItsEricSun , @nickpfeiffer05 
- Add logic to unsubscribe phone number 
- from notifs 
- when STOP_ALL reply
**Primary**: @ananyaspatil
Use the **"Reviewers"** feature in Github
Secondary reviewers:
**Secondary**:
@cherman23 
@mehallhm 
@WesleyTran0 
@nickpfeiffer05 
@ItsEricSun
> Add logic to unsubscribe phone number from notifs when STOP_ALL reply

- package.json
- yarn.lock
Upgrade Prisma to v6. Keeping on top of major version bumps
> No ticket has been created for this PR
- Upgraded Prisma to version 6 (breaking change)
- ...yet nothing broke so it was easy
> Upgrade to Prisma v6

- scrapers/classes/parsersxe/classParser.ts
Removed the weird tags in the course description from the description in the backend.
#239 
-
@WesleyTran0 
@mehallhm Thank you for the help <3
- sliced the decoded message pulled from banner
- added a comment explaining what was sliced out
- Pick one primary reviewer
- The team member with the most relevant knowledge about the code area this PR touches
- **NOT** an author of the PR
- If the primary reviewer is the project lead, _select two primary reviewers_
- Goal: facilitate knowledge transfer to other team members
- Primary reviewers **are required to approve the PR** before it can be merged
**Primary**:
Use the **"Reviewers"** feature in Github
@mehallhm @ananyaspatil 
Secondary reviewers:
@ItsEricSun @cherman23 @nickpfeiffer05 
**Secondary**:
> Sliced the description to exclude the section tags
